apiVersion: v1
kind: Service
metadata:
  name: helloworld-app
  labels:
    app: helloworld-app
spec:
  selector:
    app: helloworld-app
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http